pipeline {
    
    agent {
        
        node
        {
            
            label 'docker'
        
      
            
        }
          
        
    }
    
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'docker run maven:3-5-alpine'
                sh 'mvn --version'
            }
        }
    }
        
    }

