pipeline {
    
    agent {
        
        
      
            docker 'maven:3-5-alpine'
        }
          
        
    
    
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
               
                sh 'mvn --version'
            }
        }
    }
        
    }

