pipeline {
    
    agent {
        node {
            label 'docker'
          
        }
    }
    
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'docker run -d hello-world'
            }
        }
    }
        
    }
}
